/**
 * Storage abstraction. Keys are generated by the platform (never derived from user input):
 *
 *   jobs/<jobId>/in/<inputId>
 *   jobs/<jobId>/out/<outputId>
 */
export interface StoredObject {
  key: string;
  size: number;
  contentType: string | null;
}

export interface SignedRequest {
  method: 'PUT' | 'GET';
  url: string;
  /** Headers the client must send (upload) — part of the signature. */
  headers: Record<string, string>;
  expiresAt: string;
}

export interface UploadUrlOptions {
  contentType: string;
  /** Exact size of the upload in bytes; enforced by the signature and verified afterwards. */
  size: number;
  expiresIn: number;
}

export interface DownloadUrlOptions {
  filename: string;
  contentType: string;
  expiresIn: number;
}

export interface Storage {
  readonly driver: 'memory' | 'local' | 's3';
  createUploadUrl(key: string, options: UploadUrlOptions): Promise<SignedRequest>;
  createDownloadUrl(key: string, options: DownloadUrlOptions): Promise<SignedRequest>;
  head(key: string): Promise<StoredObject | null>;
  /** Reads bytes `[start, end]` (inclusive), clamped to the object size. */
  readRange(key: string, start: number, end: number): Promise<Uint8Array>;
  read(key: string): Promise<ReadableStream<Uint8Array>>;
  write(
    key: string,
    body: Uint8Array | ReadableStream<Uint8Array>,
    options: { contentType: string; size: number },
  ): Promise<void>;
  delete(key: string): Promise<void>;
  deleteMany(keys: readonly string[]): Promise<void>;
}

const KEY_PATTERN = /^jobs\/job_[a-z2-7]{26}\/(in|out)\/(in|out)_[a-z2-7]{26}$/;

/** Validates platform-generated keys; anything else is a programming error. */
export function assertValidKey(key: string): void {
  if (!KEY_PATTERN.test(key)) throw new Error(`invalid storage key: ${key}`);
}

export function inputKey(jobId: string, inputId: string): string {
  return `jobs/${jobId}/in/${inputId}`;
}

export function outputKey(jobId: string, outputId: string): string {
  return `jobs/${jobId}/out/${outputId}`;
}
