import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { newId } from '@vanillate/core';
import { afterAll, describe, expect, it } from 'vitest';

import {
  inputKey,
  LocalStorage,
  MemoryStorage,
  readAll,
  S3Storage,
  signToken,
  storageFromEnv,
  verifyToken,
  type Storage,
} from '../src/index.ts';

const root = mkdtempSync(join(tmpdir(), 'vc-storage-'));
afterAll(() => rmSync(root, { recursive: true, force: true }));

const secret = 'test-secret-that-is-long-enough-1234567890';
const key = (): string => inputKey(newId('job'), newId('in'));
const bytes = new TextEncoder().encode('hello vanillate');

function streamOf(data: Uint8Array): ReadableStream<Uint8Array> {
  return new ReadableStream({
    start(controller) {
      controller.enqueue(data.subarray(0, 5));
      controller.enqueue(data.subarray(5));
      controller.close();
    },
  });
}

describe.each<[string, () => Storage]>([
  ['memory', () => new MemoryStorage()],
  ['local', () => new LocalStorage({ root, signingSecret: secret, publicPath: '/api/v1/storage' })],
])('%s storage', (_name, create) => {
  const storage = create();

  it('writes, heads, reads ranges and deletes', async () => {
    const k = key();
    await storage.write(k, streamOf(bytes), { contentType: 'text/plain', size: bytes.length });
    expect((await storage.head(k))?.size).toBe(bytes.length);
    expect(new TextDecoder().decode(await storage.readRange(k, 6, 100))).toBe('vanillate');
    expect(new TextDecoder().decode(await readAll(await storage.read(k)))).toBe('hello vanillate');
    await storage.deleteMany([k]);
    expect(await storage.head(k)).toBeNull();
  });

  it('enforces the exact upload size', async () => {
    const k = key();
    await expect(
      storage.write(k, streamOf(bytes), { contentType: 'text/plain', size: bytes.length - 1 }),
    ).rejects.toThrow();
    await expect(
      storage.write(k, bytes, { contentType: 'text/plain', size: bytes.length + 1 }),
    ).rejects.toThrow();
    expect(await storage.head(k)).toBeNull();
  });

  it('rejects keys that were not generated by the platform', async () => {
    await expect(
      storage.write('../../etc/passwd', bytes, { contentType: 'x/y', size: bytes.length }),
    ).rejects.toThrow('invalid storage key');
    await expect(
      storage.createUploadUrl('jobs/x/in/y', { contentType: 'x/y', size: 1, expiresIn: 60 }),
    ).rejects.toThrow();
  });
});

describe('signed tokens', () => {
  it('verifies valid tokens and rejects tampering and expiry', async () => {
    const params = {
      key: key(),
      method: 'PUT' as const,
      expires: Math.floor(Date.now() / 1000) + 60,
      contentType: 'image/png',
      size: 10,
    };
    const token = await signToken(secret, params);
    expect(await verifyToken(secret, token)).toEqual({ ok: true, params });
    expect((await verifyToken('another-secret-that-is-long-enough-123456', token)).ok).toBe(false);
    const [payload, signature] = token.split('.');
    const forged = Buffer.from(JSON.stringify({ ...params, size: 10_000_000 })).toString(
      'base64url',
    );
    expect(await verifyToken(secret, `${forged}.${signature}`)).toEqual({
      ok: false,
      reason: 'signature',
    });
    expect(await verifyToken(secret, `${payload}`)).toEqual({ ok: false, reason: 'malformed' });
    const expired = await signToken(secret, { ...params, expires: 1 });
    expect(await verifyToken(secret, expired)).toEqual({ ok: false, reason: 'expired' });
  });

  it('local upload URLs carry a token for the storage route', async () => {
    const storage = new LocalStorage({
      root,
      signingSecret: secret,
      publicPath: '/api/v1/storage/',
    });
    const k = key();
    const upload = await storage.createUploadUrl(k, {
      contentType: 'image/png',
      size: 42,
      expiresIn: 300,
    });
    expect(upload.url).toMatch(/^\/api\/v1\/storage\/[\w-]+\.[\w-]+$/);
    const check = await verifyToken(secret, upload.url.split('/').pop()!);
    expect(check.ok && check.params).toMatchObject({
      key: k,
      method: 'PUT',
      size: 42,
      contentType: 'image/png',
    });
  });
});

describe('S3 presigning', () => {
  const s3 = new S3Storage({
    endpoint: 'https://example.r2.cloudflarestorage.com',
    region: 'auto',
    bucket: 'vanillate',
    accessKeyId: 'AKIDEXAMPLE',
    secretAccessKey: 'wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY',
    forcePathStyle: true,
  });

  it('signs content-type and content-length into upload URLs', async () => {
    const k = key();
    const upload = await s3.createUploadUrl(k, {
      contentType: 'video/mp4',
      size: 1234,
      expiresIn: 900,
    });
    const url = new URL(upload.url);
    expect(url.origin + url.pathname).toBe(
      `https://example.r2.cloudflarestorage.com/vanillate/${k}`,
    );
    expect(url.searchParams.get('X-Amz-SignedHeaders')).toBe('content-length;content-type;host');
    expect(url.searchParams.get('X-Amz-Expires')).toBe('900');
    expect(url.searchParams.get('X-Amz-Signature')).toMatch(/^[0-9a-f]{64}$/);
    expect(upload.headers).toEqual({ 'content-type': 'video/mp4', 'content-length': '1234' });
  });

  it('sets the download filename via response-content-disposition', async () => {
    const download = await s3.createDownloadUrl(key(), {
      filename: 'hasil konversi.mp4',
      contentType: 'video/mp4',
      expiresIn: 60,
    });
    const url = new URL(download.url);
    expect(url.searchParams.get('response-content-disposition')).toContain(
      "filename*=UTF-8''hasil%20konversi.mp4",
    );
    expect(url.searchParams.get('response-content-type')).toBe('video/mp4');
  });

  it('supports virtual-hosted style URLs', () => {
    const virtual = new S3Storage({
      endpoint: 'https://s3.ap-southeast-1.amazonaws.com',
      region: 'ap-southeast-1',
      bucket: 'vc',
      accessKeyId: 'a',
      secretAccessKey: 'b',
      forcePathStyle: false,
    });
    const k = key();
    expect(virtual.objectUrl(k)).toBe(`https://vc.s3.ap-southeast-1.amazonaws.com/${k}`);
  });
});

describe('storageFromEnv', () => {
  it('builds drivers from environment variables', () => {
    expect(storageFromEnv({})).toBeNull();
    expect(storageFromEnv({ STORAGE_DRIVER: 'memory' })?.driver).toBe('memory');
    expect(
      storageFromEnv({
        STORAGE_DRIVER: 'local',
        STORAGE_LOCAL_DIR: root,
        STORAGE_SIGNING_SECRET: secret,
      })?.driver,
    ).toBe('local');
    expect(() =>
      storageFromEnv({
        STORAGE_DRIVER: 'local',
        STORAGE_LOCAL_DIR: root,
        STORAGE_SIGNING_SECRET: 'short',
      }),
    ).toThrow('32');
    expect(() => storageFromEnv({ STORAGE_DRIVER: 's3' })).toThrow('S3_ENDPOINT');
    expect(() => storageFromEnv({ STORAGE_DRIVER: 'ftp' })).toThrow('unknown');
  });
});
