/**
 * Generates docs/CONVERSION-MATRIX.md from the registry, so the documented matrix is always
 * the one the platform offers.
 *
 *   pnpm docs:matrix            write the file
 *   pnpm docs:matrix --check    fail if the file is out of date (CI)
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  getRegistry,
  STATUSES,
  type Conversion,
  type Registry,
  type Status,
} from '@vanillate/core';

const outFile = join(import.meta.dirname, '..', 'docs', 'CONVERSION-MATRIX.md');
const check = process.argv.includes('--check');

/** Statuses a conversion can be offered with, best first. */
const OFFERED: readonly Status[] = STATUSES.filter((s) => s !== 'unsupported');

const count = (list: readonly Conversion[], status: Status): number =>
  list.filter((c) => c.status === status).length;

const withConversions = (registry: Registry): number =>
  registry.formats.filter((f) => f.readable || f.writable).length;

function target(conversion: Conversion): string {
  return conversion.modes.includes('browser') ? `${conversion.to}\\*` : conversion.to;
}

function summary(full: Registry, browserOnly: Registry): string[] {
  const offered = full.offeredConversions();
  const browser = offered.filter((c) => c.modes.includes('browser'));
  const lines = [
    '## Summary',
    '',
    '| | Full deployment | Browser-only deployment |',
    '| --- | ---: | ---: |',
    `| Formats in the catalog | ${full.formats.length} | ${browserOnly.formats.length} |`,
    `| Formats with offered conversions | ${withConversions(full)} | ${withConversions(browserOnly)} |`,
    `| Conversions offered | ${offered.length} | ${browserOnly.offeredConversions().length} |`,
    `| Indexable conversion pages | ${full.indexableConversions().length} | ${browserOnly.indexableConversions().length} |`,
    `| Tools offered | ${full.offeredTools().length} | ${browserOnly.offeredTools().length} |`,
    `| Conversions that can run in the browser | ${browser.length} | ${browserOnly.offeredConversions().length} |`,
    '',
    '| Status | Conversions |',
    '| --- | ---: |',
    ...OFFERED.map((status) => `| ${status} | ${count(offered, status)} |`),
    '',
  ];
  return lines;
}

function byCategory(registry: Registry): string[] {
  const lines = ['## Conversions by source format', ''];
  lines.push(
    'Targets marked `*` can run in the browser; the others run on the server. Experimental',
    'conversions are offered with a warning and are not indexed.',
    '',
  );
  for (const category of registry.categories) {
    const formats = category.formatIds
      .map((id) => registry.requireFormat(id))
      .filter((format) => registry.conversionsFrom(format.id).length > 0);
    if (formats.length === 0) continue;
    lines.push(`### ${category.name.en}`, '');
    lines.push('| From | Stable | Supported | Limited | Experimental |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const format of formats) {
      const conversions = [...registry.conversionsFrom(format.id)].sort((a, b) =>
        a.to.localeCompare(b.to),
      );
      const cell = (status: Status): string =>
        conversions
          .filter((c) => c.status === status)
          .map(target)
          .join(', ') || '—';
      lines.push(
        `| **${format.label}** (\`${format.id}\`) | ${cell('stable')} | ${cell('supported')} | ${cell('limited')} | ${cell('experimental')} |`,
      );
    }
    lines.push('');
  }
  return lines;
}

function tools(registry: Registry): string[] {
  const lines = [
    '## Tools',
    '',
    '| Tool | Inputs | Output | Status | Routes |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const tool of [...registry.offeredTools()].sort((a, b) => a.id.localeCompare(b.id))) {
    const routes = tool.routes
      .filter((r) => r.offered)
      .map((r) => `${r.engine} (${r.mode}, ${r.status})`)
      .join('; ');
    const inputs = tool.inputs.includes('*') ? 'any file' : tool.inputs.join(', ');
    lines.push(
      `| ${tool.name.en} (\`${tool.id}\`) | ${inputs} | ${tool.output} | ${tool.status} | ${routes} |`,
    );
  }
  lines.push('');
  return lines;
}

function notOffered(registry: Registry): string[] {
  const missing = registry.conversions.filter((c) => !c.offered);
  if (missing.length === 0) return [];
  return [
    '## Defined but not offered',
    '',
    'Routes exist in the catalog, but every route is disabled, unsupported or needs an engine',
    'that is not available:',
    '',
    ...missing.map((c) => `- \`${c.from}\` → \`${c.to}\``),
    '',
  ];
}

const full = getRegistry();
const browserOnly = getRegistry({ disabledModes: ['server'] });
const content = [
  '# Conversion Matrix',
  '',
  '<!-- Generated by scripts/docs-matrix.ts from the catalog. Do not edit by hand: run `pnpm docs:matrix`. -->',
  '',
  'Every conversion the platform offers, generated from the registry (`catalog/`). A',
  'conversion is offered only when an available engine supports it with a status other than',
  '`unsupported` — see [FORMAT-REGISTRY.md](FORMAT-REGISTRY.md) for how routes and statuses',
  'are derived, and [ENGINE-MAPPING.md](ENGINE-MAPPING.md) for the engines behind them.',
  '',
  ...summary(full, browserOnly),
  ...byCategory(full),
  ...tools(full),
  ...notOffered(full),
].join('\n');

if (check) {
  if (!existsSync(outFile) || readFileSync(outFile, 'utf8') !== content) {
    console.error('✗ docs/CONVERSION-MATRIX.md is out of date — run pnpm docs:matrix');
    process.exit(1);
  }
  console.log('✓ docs/CONVERSION-MATRIX.md is up to date');
} else {
  writeFileSync(outFile, content);
  console.log(`wrote docs/CONVERSION-MATRIX.md (${full.offeredConversions().length} conversions)`);
}
